version: '3.8'

services:
  bets:
    build: .
    container_name: bets
    image: backend
    restart: always
    command: ["python", "manage.py", "runserver",
              "0.0.0.0:8000"]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7.0
    container_name: redis

  celery_worker:
    build: .
    container_name: worker
    image: celery_worker
    command: celery -A favbet worker -l info -Q first
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - bets
      - redis

  celery_worker2:
    build: .
    container_name: worker2
    image: celery_worker2
    command: celery -A favbet worker -l info -Q second
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - bets
      - redis

  celery_beat:
    build: .
    container_name: scheduler
    image: celery_beat
    command: ["celery", "-A", "favbet", 
              "beat", "-l", "info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - celery_worker
      - celery_worker2

volumes:
  data: